"""FastAPI app exposing /healthz and /webhook/message.

The webhook handler stitches the C1-C3 pieces together:
  InboundWebhook -> UnifiedMessage -> draft_reply -> score_and_act -> EndpointResponse.

PLAN S15 C4 fixes the contract:
- 422 on malformed payloads (FastAPI handles this automatically from Pydantic).
- 503 on Claude timeout, 429 on rate limit, 502 on any other Claude failure.
- message_id is generated by UnifiedMessage.from_inbound BEFORE the Claude call,
  so it appears in every error body for client-side correlation.
- Don't log the full guest message text (PII per PLAN anti-patterns); log
  message_id + source + length only at INFO.
"""
import logging

from fastapi import FastAPI, HTTPException

from src.claude_client import (
    ClaudeRateLimitError,
    ClaudeServiceError,
    ClaudeTimeoutError,
    draft_reply,
)
from src.confidence import score_and_act
from src.models import EndpointResponse, InboundWebhook, UnifiedMessage


logger = logging.getLogger(__name__)

app = FastAPI(
    title="Nistula Message Handler",
    description=(
        "Webhook backend that ingests guest messages from multiple channels, "
        "drafts replies via Anthropic Claude, and assigns a confidence-scored "
        "action. See PLAN.md and README.md."
    ),
    version="0.1.0",
)


@app.get("/healthz")
def healthz() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/webhook/message", response_model=EndpointResponse)
def webhook_message(inbound: InboundWebhook) -> EndpointResponse:
    """Validate the inbound webhook, draft a reply, score it, and respond.

    Sync handler (FastAPI runs sync handlers in a threadpool) because the
    Anthropic SDK call is blocking; making this `async def` would block the
    event loop on every webhook.
    """
    unified = UnifiedMessage.from_inbound(inbound)
    logger.info(
        "webhook received message_id=%s source=%s message_len=%d",
        unified.message_id,
        unified.source,
        len(unified.message_text),
    )

    try:
        claude_output = draft_reply(unified)
    except ClaudeTimeoutError as exc:
        logger.warning("webhook 503 timeout message_id=%s", unified.message_id)
        raise HTTPException(
            status_code=503,
            detail={
                "message_id": str(unified.message_id),
                "error": "Upstream timeout, retry recommended",
            },
        ) from exc
    except ClaudeRateLimitError as exc:
        logger.warning("webhook 429 rate_limit message_id=%s", unified.message_id)
        raise HTTPException(
            status_code=429,
            detail={
                "message_id": str(unified.message_id),
                "error": "Upstream rate limit, retry after a short delay",
            },
        ) from exc
    except ClaudeServiceError as exc:
        logger.error(
            "webhook 502 service_error message_id=%s reason=%s",
            unified.message_id,
            exc,
        )
        raise HTTPException(
            status_code=502,
            detail={
                "message_id": str(unified.message_id),
                "error": "Upstream service error",
            },
        ) from exc

    score, action = score_and_act(claude_output, unified)
    logger.info(
        "webhook completed message_id=%s action=%s score=%.3f",
        unified.message_id,
        action,
        score,
    )

    return EndpointResponse(
        message_id=unified.message_id,
        query_type=claude_output.query_type,
        drafted_reply=claude_output.drafted_reply,
        confidence_score=score,
        action=action,
    )
